decide=str(input('Valley to standars?(Y/N)'))
from math import pi,cos,sin,atan
if decide=='Y' or decide=='y':
    kos=float(input('value of KOS(else enter zero):'))
    nk=kos*15*sin(pi+atan((-sin(pi/18))/cos(pi/18)))
    ek=kos*15*cos(pi+atan((-sin(pi/18))/cos(pi/18)))
    print(nk,'Along North in km')
    print(ek,'Along East in km')
    bans=float(input('Value of BANS(else enter zero):'))
    nb=bans*0.2*cos(atan((-sin(pi/18))/cos(pi/18)))
    eb=bans*0.2*sin(atan((-sin(pi/18))/cos(pi/18)))
    print(nb,'Along North in km')
    print(eb,'Along East in km')
else:
    east=float(input('Distance in km along East:'))
    be=5*east/cos(atan((-sin(pi/18))/cos(pi/18)))
    ke=-east/(15*cos(atan((-sin(pi/18))/cos(pi/18))))
    print('BANS towars lighthouse:',be)
    print('KOS towards high peak:',ke)
    north=float(input('Distance in km along North:'))
    kn=north/(15*sin(pi+atan((-sin(pi/18))/cos(pi/18))))
    bn=5*north/sin(atan((-sin(pi/18))/cos(pi/18)))
    print(kn,'KOS towards high peak')
    print(bn,'BANS towards lighthouse')
q=str(input('Press enter to exit'))
